name: Build and Release Electron App

on:
  push:
    branches:
      - main # or any other branch you want

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, linux]
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Wine on Windows
        if: matrix.platform == 'win'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine64 wine32

      - name: Install dependencies
        run: pnpm install

      - name: Install Wine on Windows
        if: matrix.platform == 'mac'
        run: |
          pnpm i -D dmg-license

      - name: Build and package app for ${{ matrix.platform }}
        run: pnpm run build:${{ matrix.platform }}

      - name: Upload dist ZIP to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "body.md"

