name: Build and Release Electron App

on:
  push:
    branches:
      - main # or any other branch you want

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [win, linux]
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build and package app for ${{ matrix.platform }}
        run: pnpm run build:${{ matrix.platform }}

      - name: Zip dist folder
        run: zip -r dist-${{ matrix.platform }}.zip dist/

      - name: Upload dist ZIP to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.platform }}
          path: dist-${{ matrix.platform }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Windows
        if: contains(github.ref, 'win')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-win.zip
          asset_name: dist-win.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Mac
        if: contains(github.ref, 'mac')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-mac.zip
          asset_name: dist-mac.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Linux
        if: contains(github.ref, 'linux')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist-linux.zip
          asset_name: dist-linux.zip
          asset_content_type: application/zip
